### ISSUE TITLE
Validation issue with example_webhook_test.go

### ISSUE THREAD

**Issue by tjdavis3** [standard-webhooks/standard-webhooks#101]
In the go example there is a very high probability that it will fail validation.  In the following line the signature is created using `time.Now()`.  However, the header is set in line 42 using `ts.Unix()` and ts was created at the top of the function (also using time.Now()).  The difference may be in the milliseconds range, but it could be enough to cause a validation failure.  The correct way to do it would be to use the `ts` value when creating the signature.

https://github.com/standard-webhooks/standard-webhooks/blob/6b5ecd10fde25fd317dea72e187e212091d4c72d/libraries/go/example_webhook_test.go#L32

**Comment by jorgelob** [comment]
That's a very valid point. A millisecond drift could make this validation fail.
