### ISSUE TITLE
Verify webhook / Simulate Webhook Request issues

### ISSUE THREAD

**Issue by 6juara9** [standard-webhooks/standard-webhooks#111]
It seems like these 2 pages works incorrectly for `standard webhook` type:
- https://www.standardwebhooks.com/simulate
- https://www.standardwebhooks.com/verify

I tried to verify my own created webhook and also simulated using [this page](https://www.standardwebhooks.com/simulate) but it is different from the description in specs + different from multiple online clients. 

**PS: I know that it appends v1 prefix but still it is different, see the pictures below. Shopify webhook type works correctly on the other hand (probably other types as well)**

**Simulated one**

- https://www.standardwebhooks.com/simulate

![image](https://github.com/standard-webhooks/standard-webhooks/assets/33040515/712220c6-91aa-4ac0-930b-486e3121ccd7)

**Other clients**

- https://www.devglan.com/online-tools/hmac-sha256-online

![image](https://github.com/standard-webhooks/standard-webhooks/assets/33040515/a2ac1037-3284-43cf-9273-c38f0f5ea947)

- https://www.javainuse.com/hmac

![Screenshot 2024-02-05 at 15 50 10](https://github.com/standard-webhooks/standard-webhooks/assets/33040515/85cf60e1-c3d5-4a0a-94ce-b1f6dea52877)

**Comment by J0** [comment]
Hi,

I was able to successfully use the tools recently to verify and simulate a request payload. I think the [secret key prefix is dropped](https://github.com/standard-webhooks/standard-webhooks/blob/main/libraries/javascript/src/index.ts#L52) before signing and the key comes encoded

You might need to drop the `whsec_` and use a `base64` decoded secret if working with a vanilla HMAC signing tool. If you paste the relevant code snippets as text I might be able to help check / debug.

Hope this helps!

**Comment by tasn** [comment]
Whoops, I completely missed this ticket. Thanks @J0!
