### ISSUE TITLE
Ruby library

### ISSUE THREAD

**Issue by sandstrom** [standard-webhooks/standard-webhooks#158]
Great standard, was looking for something like this for our site.

However, the ruby library looks kind of weird:

- 4 vs. 2 spaces for indent
- private constants aren't really private (https://blog.toshima.ru/2020/02/22/ruby-private-constant.html)
- explicit return is not common in ruby
- `symbolize_names` on JSON.parse is somewhat unexpected.
    
    > “If the contents (the sequence of characters) of the object are important, use a string. If the identity of the object is important, use a symbol.”

If you want I can provide a PR with some adjustments. I won't change any of the actual code though, just syntax, making constants private, etc.

**Comment by sandstrom** [comment]
@zekth I've opened a PR: https://github.com/standard-webhooks/standard-webhooks/pull/192

**Comment by tasn** [comment]
Yay, thanks for the PR!
