### ISSUE TITLE
spec: signing the headers

### ISSUE THREAD

**Issue by hf** [standard-webhooks/standard-webhooks#26]
It's not super clear whether the headers of the HTTP message are also signed under `webhook-signature`. This should generally be the case so that they too are authenticated. This probably requires adding a section about canonicalizing the headers and including them in the signature computation.

**Comment by zekth** [comment]
So the signature would sign all the headers except the `webhook-signature` one right?
That sounds a legitimate but i have a question:
On the consumer side what would happen then when the request goes to `N` proxies before landing to the webhook handler? If any proxy mutates the http headers it would fail no? There's many doing so. eg:
In `Kong` you can setup keys for a route via a concept of `consumer` and this route will add headers related to the identication of this key. ref: https://docs.konghq.com/hub/kong-inc/key-auth/#upstream-headers

**Comment by tasn** [comment]
Under the current spec (we probably should clarify that), they would indeed not be signed. There are two reasons for that: (1) what @zekth said about all the intermediary that could potentially modify the headers, and (2) they shouldn't hold any information of significance. Per the per spec the data should only be sent as part of the payload, so as long as that's verified, everything that matters is verified. Verifying the headers should therefore not add any security.

One additional challenge that you just mentioned is the rabbit hole of canonicalizing headers. I think it would be immensely difficult to maintain a consistent behavior across different implementations. So even if we wanted it, I think it's going to add a tonne of complexity.

**Comment by hf** [comment]
> So the signature would sign all the headers except the `webhook-signature` one right? That sounds a legitimate but i have a question:
> 
> On the consumer side what would happen then when the request goes to `N` proxies before landing to the webhook handler? If any proxy mutates the http headers it would fail no? There's many doing so. eg: In `Kong` you can setup keys for a route via a concept of `consumer` and this route will add headers related to the identication of this key. ref: https://docs.konghq.com/hub/kong-inc/key-auth/#upstream-headers

That's fine. Not all headers should participate in the signature. And in any case, if the intermediary is trusted, it can have access to the private key and recompute the signature if necessary.

> Under the current spec (we probably should clarify that), they would indeed not be signed. There are two reasons for that: (1) what @zekth said about all the intermediary that could potentially modify the headers, and (2) they shouldn't hold any information of significance. Per the per spec the data should only be sent as part of the payload, so as long as that's verified, everything that matters is verified. Verifying the headers should therefore not add any security.

Ah but this is the problem. For example, the spec says check `webhook-id` and `webhook-timestamp` but me as an attacker, I can choose any value for those. So I can replay the same message with its valid signature, and vary those two headers to my choosing.

Had they been included in the signature, the whole payload would be immediately rejected if I tried to do anything like that.

> One additional challenge that you just mentioned is the rabbit hole of canonicalizing headers. I think it would be immensely difficult to maintain a consistent behavior across different implementations. So even if we wanted it, I think it's going to add a tonne of complexity.

We can say something like:

- All `webhook-` prefixed headers are sorted alphabetically.
- Concatenated in their original form, i.e. `webhook-xyz: abc\n\r`.
- Prepended to the body in its original form.
- Finally signature is computed.

**Comment by zekth** [comment]
My bad i forgot this part.
For ref:
https://github.com/standard-webhooks/standard-webhooks/blob/d6b7156598536e02a5ff898984e55f63dd208298/libraries/go/webhook.go#L94-L118

**Comment by teliosdev** [comment]
I'm not sure if this might be of interest to the project, but there is a "HTTP message signatures" [RFC standard draft](https://datatracker.ietf.org/doc/draft-ietf-httpbis-message-signatures/) which might work for this use case.

**Comment by tasn** [comment]
Hey @teliosdev, thanks for the link! We are familiar with the RFC (it's even mentioned in the README!). There were a few reasons, but one of the main ones is: one of the design goals of this spec is to meet people where they are. So following but cementing industry best practices, rather than trying to do something very different. It's much better to have a great spec that's widely adopted than a perfect one that's used by no one. With that being said, as HTTP message signatures become more widespread/widely supported, this recommendation will probably change (future version of the spec).

**Comment by tasn** [comment]
I'm closing this ticket, as the original issue is resolved (headers are signed).
