### ISSUE TITLE
Typo on Technical Steering Committee

### ISSUE THREAD

**Issue by simonw** [standard-webhooks/standard-webhooks#31]
On https://www.standardwebhooks.com/#committee

![Stojan Dimitrovski Authentication Lead at Supbase](https://github.com/standard-webhooks/standard-webhooks/assets/9599/3593bfc5-a097-43e9-9a77-2cddca38e2d8)

Should be Supabase, not Supbase.

**Comment by tasn** [comment]
Nice catch, thanks @simonw!
