### ISSUE TITLE
libraries(python): Improve python build system

### ISSUE THREAD

**Issue by sudosubin** [standard-webhooks/standard-webhooks#47]
The usage of `python setup.py` (as a command line tool) is deprecated according to [this document](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/).

https://github.com/standard-webhooks/standard-webhooks/blob/ce813cd1f5e5d6e8da1a2eb35af1266151af422c/.github/workflows/python-release.yml#L32-L35

It would be better to use [`build`](https://github.com/pypa/build) instead. `build` is a simple python packaging build frontend.

- `pip install build~=1.0.3`
- `pyproject-build . --sdist` (not generating `.whl` file)

When I tested in a local environment, I confirmed that it worked without any code change. (but specifying `build-system` in `pyproject.toml` is recommended) After `build` is used, the python library can define package specifications declaratively in `pyproject.toml` according to [PEP 517](https://peps.python.org/pep-0517/), and [PEP 518](https://peps.python.org/pep-0518/).

How do you think? Before the contribution, I'd like to ask maintainers for the opinions.

**Comment by tasn** [comment]
I think it sounds reasonable, I'm a bit removed from the Python ecosystem at the moment. @zekth, got any thoughts?

**Comment by zekth** [comment]
Lgtm happy to review the PR

**Comment by sudosubin** [comment]
thanks :) I made a [PR](https://github.com/standard-webhooks/standard-webhooks/pull/52) for this issue.
