### ISSUE TITLE
Elixir library

### ISSUE THREAD

**Issue by cpursley** [standard-webhooks/standard-webhooks#58]
I've been working on adding Standard Webhooks support for [webhoox](https://github.com/cpursley/webhoox/blob/master/lib/webhoox/authentication/standard_webhook.ex) (tests [here](https://github.com/cpursley/webhoox/blob/master/test/authentication/standard_webhook_test.exs)).

I'd be glad to bring the relevant parts over into this repo.

**Comment by tasn** [comment]
Yes, we would love that, thanks a lot. Please open a PR! 🙏🏻

**Comment by cpursley** [comment]
https://github.com/standard-webhooks/standard-webhooks/pull/87

**Comment by zekth** [comment]
Closing as it has been adressed.
